cojung/urls.py
from django.urls import path
from .views import resolve_views, problem_views, question_views, post_views, vote_views, answer_views, comment_views

app_name = 'cojung'

urlpatterns = [
    #Problem Line --
    path('', problem_views.index, name='index'),
    path('problem/<int:problem_id>/',problem_views.detail, name='detail'),
 
    # 어려워요 ,쉬워요 비교문  
    path('problem/hard/<int:problem_id>',vote_views.harder,name='hard'),
    path('problem/easy/<int:problem_id>',vote_views.easyer,name='easy'),
    path('problem/both/<int:problem_id>',vote_views.both,name='both'),
      
    #Question Line --
    path('question/', question_views.question, name = 'question'),
    path('question/<int:question_id>', question_views.question_detail, name = 'question_detail'),
    path('question/modify/<int:question_id>', question_views.question_modify, name = 'question_modify'),
    path('question/delete/<int:question_id>', question_views.question_delete, name = 'question_delete'),
    
    #Answer Line --
    path('answer/create/<int:question_id>', answer_views.answer_create, name = 'answer_create'),
    path('answer/modify/<int:answer_id>', answer_views.answer_modify, name = 'answer_modify'),
    path('answer/delete/<int:answer_id>', answer_views.answer_delete, name = 'answer_delete'),

    # 문제 업로드 / 질문 작성
    path('createpost/', post_views.create_post, name='create_post'),
    path('createquestion/', post_views.create_question, name='create_question'),
    
    #Comment Line --
    path('comment/create/<int:answer_id>', comment_views.comment_answer_create, name = 'comment_answer_create'),
    path('comment/modify/<int:comment_id>', comment_views.comment_answer_modify, name = 'comment_answer_modify'),
    path('comment/delete/<int:comment_id>', comment_views.comment_answer_delete, name = 'comment_answer_delete'),

    #풀이 생성 ,댓글
    path('resolve/detail/<int:problem_id>/',resolve_views.resolve_detail,name='resolve_detail'),
    path('resolve/<int:problem_id>/',resolve_views.Resolve_create,name='resolve_create'),
    path('resolve/modify/<int:resolve_id>/', resolve_views.resolve_modify, name='resolve_modify'),
    path('resolve/delete/<int:resolve_id>/', resolve_views.resolve_delete, name='resolve_delete'),
    path('comment/create/resolve/<int:resolve_id>',resolve_views.comment_create_resolve,name='comment_create_resolve'),
    path('createquestion/', post_views.create_question, name='create_question'),
    path('problem/modify/<int:problem_id>/', problem_views.problem_modify, name='problem_modify'),
    path('problem/delete/<int:problem_id>/', problem_views.problem_delete, name='problem_delete'),


    # 문제 업로드 / 질문 작성
    path('createquestion2/<int:problem_id>', post_views.create_question_problem, name='create_question_problem'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from cojung.views import problem_views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', problem_views.index, name="index"),
    path("admin/", admin.site.urls),
    path("cojung/", include('cojung.urls')),
    path("member/", include('member.urls')),
]
# 파일 첨부를 위한  media 경로 추가
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

member/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "member"

urlpatterns = [
    path("login/", auth_views.LoginView.as_view(template_name="member/login.html"), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", views.signup, name="signup"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko-kr">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>코딩의 정석</title>
    <!--fontawesome / bt4 / css-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ==" crossorigin="anonymous" referrerpolicy="no-referrer"/>
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

    
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.3/dist/jquery.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>
    {% block style %}{% endblock style %}
  </head>

  <body>
    <!--narvbar.html 불러오기-->
    {% include 'narvbar.html' %}

    <!--공통 템플릿-->
    <div class="container my-3">
      {% block content %}{% endblock content %}
    </div>

    <script src="{% static 'bootstrap.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.3/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>

    {% block script %}{% endblock script %}
  </body>

</html>

templates/buttons.html
<div class='d-flex flex-row-reverse mb-3'>
  <a href="{% url 'cojung:create_question' %}" class='btn'>
    <i class="fa-regular fa-circle-question"></i>
    질문작성
  </a>
  <a href="{% url 'cojung:create_post' %}" class='btn'>
    <i class="fa-regular fa-note-sticky"></i>
    문제 업로드
  </a>
</div>

templates/form_errors.html
{% if form.errors %}
  {% for field in form %}
    {% for error in field.errors %}
      <div class="alert alert-danger">
        <strong>{{ field.label }}</strong>
        {{ error }}
      </div>
    {% endfor %}
  {% endfor %}
  {% for error in form.non_field_errors %}
    <div class="alert alert-danger">
      <strong>{{ error }}</strong>
    </div>
  {% endfor %}
{% endif %}

templates/narvbar.html
<nav class="navbar navbar-expand-sm bg-light navbar-light fixed-top">
  <!-- Brand -->
  <a class="navbar-brand" href="{% url 'cojung:index' %}" style = "padding-left :10px">코딩의 정석</a>

  <!--문제 풀기, 질문하기 버튼-->
  <div class = 'collapse navbar-collapse justify-content-between'>
    <!-- Links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'cojung:index' %}">코딩 문제 풀기</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'cojung:question' %}">질문하기</a>
      </li>
    </ul>
    
    <!--로그인, 로그아웃-->
    <ul class="navbar-nav">
      {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="#">
            {{user.username}}
            님 반갑습니다 !
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'member:logout' %}">
            로그아웃
          </a>
        </li>
      {% else %}
        <li class="nav-item ">
          <a class="nav-link" href="{% url 'member:login' %}">로그인</a>
        </li>
        <li>
          <a class="nav-link" href="{% url 'member:signup' %}">회원가입</a>
        </li>
      {% endif %}
    </ul>
  </div>  
</nav>

templates/pagination_problem.html
<!--페이징처리(문제 목록)-->
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

<div>
    <ul class="pagination justify-content-center">
        <!--Previous 처리-->
        {% if  problemLst.has_previous %}
            <li class="page-item">
                <a class="page-link" href="#" data-page = "1">
                    <i class="fa-solid fa-angles-left"></i>
                </a>
            </li>
            <li class="page-item">
                <a class="page-link" href="#" data-page = "{{problemLst.previous_page_number}}">
                    <i class="fa-solid fa-chevron-left"></i>
                </a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link" tabindex = "-1" aria-disabled = "true" href="#">
                    <i class="fa-solid fa-chevron-left"></i>
                </a>
            </li>
        {% endif %}

        <!--Page 번호 선택 처리-->
        {% for pageNum in problemLst.paginator.page_range %}
            {% if pageNum >= problemLst.number|add:-5 and pageNum <= problemLst.number|add:5 %}
                {% if pageNum == problemLst.number %}
                    <li class = 'page-item active' aria-current = "page">
                        <a class = "page-link" href = "#" data-page = "{{pageNum}}">
                            {{pageNum}}
                        </a>
                    </li>
                {% else %}
                    <li class = 'page-item'>
                        <a class = "page-link" href = "#" data-page = "{{pageNum}}">
                            {{pageNum}}
                        </a>
                    </li>
                {% endif %}
            {% endif %}
        {% endfor %}
        
        <!--Next 처리-->
        {% if problemLst.has_next %}
            <!--다음페이지로-->
            <li class="page-item">
                <a class="page-link" href="#" data-page = "{{problemLst.next_page_number}}">
                    <i class="fa-solid fa-angle-right"></i>
                </a>
            </li>
            <!--마지막으로-->
            <li class="page-item">
                <a class="page-link" href="#" data-page = "{{problemLst.next_page_number}}">
                    <i class="fa-solid fa-angles-right"></i>                
                </a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link" tabindex = "-1" aria-disabled = "true" href="#">
                    <i class="fa-solid fa-angle-right"></i>
                </a>
            </li>
        {% endif %}
        <!--페이징 처리 끝-->
    </ul>
</div>
<!--페이징 처리-->

templates/pagination_question.html
<!--페이징처리(질문 목록)-->

{% load static %}

<div>
    <ul class="pagination justify-content-center">
        <!--Previous 처리-->
        {% if  questionLst.has_previous %}
            <li class="page-item">
                <a class="page-link" href="#" data-page = "1">
                    <i class="fa-solid fa-angles-left"></i>
                </a>
            </li>
            <li class="page-item">
                <a class="page-link" href="#" data-page = "{{questionLst.previous_page_number}}">
                    <i class="fa-solid fa-chevron-left"></i>
                </a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link" tabindex = "-1" aria-disabled = "true" href="#">
                    <i class="fa-solid fa-chevron-left"></i>
                </a>
            </li>
        {% endif %}

        <!--Page 번호 선택 처리-->
        {% for pageNum in questionLst.paginator.page_range %}
            {% if pageNum >= questionLst.number|add:-5 and pageNum <= questionLst.number|add:5 %}
                {% if pageNum == questionLst.number %}
                    <li class = 'page-item active' aria-current = "page">
                        <a class = "page-link" href = "#" data-page = "{{pageNum}}">
                            {{pageNum}}
                        </a>
                    </li>
                {% else %}
                    <li class = 'page-item'>
                        <a class = "page-link" href = "#" data-page = "{{pageNum}}">
                            {{pageNum}}
                        </a>
                    </li>
                {% endif %}
            {% endif %}
        {% endfor %}
        
        <!--Next 처리-->
        {% if questionLst.has_next %}
            <!--다음페이지로-->
            <li class="page-item">
                <a class="page-link" href="#" data-page = "{{questionLst.next_page_number}}">
                    <i class="fa-solid fa-angle-right"></i>
                </a>
            </li>
            <!--마지막으로-->
            <li class="page-item">
                <a class="page-link" href="#" data-page = "{{questionLst.paginator.num_pages}}">
                    <i class="fa-solid fa-angles-right"></i>                
                </a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link" tabindex = "-1" aria-disabled = "true" href="#">
                    <i class="fa-solid fa-angle-right"></i>
                </a>
            </li>
        {% endif %}
        <!--페이징 처리 끝-->
    </ul>
</div>
<!--페이징 처리-->