cojung/urls.py
from django.urls import path
from .views import resolve_views, problem_views, question_views, post_views, vote_views, answer_views, comment_views

app_name = 'cojung'

urlpatterns = [
    #Problem Line --
    path('', problem_views.index, name='index'),
    path('problem/<int:problem_id>/',problem_views.detail, name='detail'),
 
    # 어려워요 ,쉬워요 비교문  
    path('problem/hard/<int:problem_id>',vote_views.harder,name='hard'),
    path('problem/easy/<int:problem_id>',vote_views.easyer,name='easy'),
    path('problem/both/<int:problem_id>',vote_views.both,name='both'),
      
    #Question Line --
    path('question/', question_views.question, name = 'question'),
    path('question/<int:question_id>', question_views.question_detail, name = 'question_detail'),
    path('question/modify/<int:question_id>', question_views.question_modify, name = 'question_modify'),
    path('question/delete/<int:question_id>', question_views.question_delete, name = 'question_delete'),
    
    #Answer Line --
    path('answer/create/<int:question_id>', answer_views.answer_create, name = 'answer_create'),
    path('answer/modify/<int:answer_id>', answer_views.answer_modify, name = 'answer_modify'),
    path('answer/delete/<int:answer_id>', answer_views.answer_delete, name = 'answer_delete'),

    # 문제 업로드 / 질문 작성
    path('createpost/', post_views.create_post, name='create_post'),
    path('createquestion/', post_views.create_question, name='create_question'),
    
    #Comment Line --
    path('comment/create/<int:answer_id>', comment_views.comment_answer_create, name = 'comment_answer_create'),
    path('comment/modify/<int:comment_id>', comment_views.comment_answer_modify, name = 'comment_answer_modify'),
    path('comment/delete/<int:comment_id>', comment_views.comment_answer_delete, name = 'comment_answer_delete'),

    #풀이 생성 ,댓글
    path('resolve/detail/<int:problem_id>/',resolve_views.resolve_detail,name='resolve_detail'),
    path('resolve/<int:problem_id>/',resolve_views.Resolve_create,name='resolve_create'),
    path('resolve/modify/<int:resolve_id>/', resolve_views.resolve_modify, name='resolve_modify'),
    path('resolve/delete/<int:resolve_id>/', resolve_views.resolve_delete, name='resolve_delete'),
    path('comment/create/resolve/<int:resolve_id>',resolve_views.comment_create_resolve,name='comment_create_resolve'),
    path('createquestion/', post_views.create_question, name='create_question'),
    path('problem/modify/<int:problem_id>/', problem_views.problem_modify, name='problem_modify'),
    path('problem/delete/<int:problem_id>/', problem_views.problem_delete, name='problem_delete'),


    # 문제 업로드 / 질문 작성
    path('createquestion2/<int:problem_id>', post_views.create_question_problem, name='create_question_problem'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from cojung.views import problem_views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', problem_views.index, name="index"),
    path("admin/", admin.site.urls),
    path("cojung/", include('cojung.urls')),
    path("member/", include('member.urls')),
]
# 파일 첨부를 위한  media 경로 추가
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cojung/models.py
from django.db import models
from django.contrib.auth.models import User
import os
import config.settings as settings

class Language(models.Model):
    name = models.CharField('언어명',max_length=100)
    
    # print
    def __str__(self):
        return self.name

# 문제
class Problem(models.Model):
    subject = models.CharField('제목', max_length=200)
    content = models.TextField('내용')
    create_date = models.DateTimeField('생성일')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='problem_author')
    modify_date = models.DateTimeField(null=True,blank=True)

    # 파일 업로드
    txtfile = models.FileField('첨부파일', null=True, upload_to="media", blank=True)
    #vote
    hard = models.ManyToManyField(User, null=True, blank=True, related_name='vote_hard_problem_user')
    easy = models.ManyToManyField(User, null=True, blank=True, related_name='vote_easy_problem_user')
    
    #languages
    language = models.ManyToManyField(Language, null = True, blank=True, related_name = 'language')

    def __str__(self):
        return f'{self.subject}'
    
    #게시글 삭제시 파일 삭제
    def delete(self, *args, **kargs):
        if self.txtfile:
            os.remove(os.path.join(settings.MEDIA_ROOT, self.txtfile.path))
        super(Problem, self).delete(*args, **kargs)

class Question(models.Model):
    subject = models.CharField('제목', max_length=200)
    content = models.TextField('내용')
    create_date = models.DateTimeField('생성일')
    modify_date = models.DateTimeField('수정일', null=True,blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    # FK
    problem = models.ForeignKey(Problem, null=True, blank=True, on_delete=models.CASCADE)
    # 파일 업로드
    txtfile = models.FileField('첨부파일', null=True, upload_to="media", blank=True)
    
    def __str__(self):
        return f'Problem : {self.problem} / {self.subject}'
    
    #게시글 삭제시 파일 삭제
    def delete(self, *args, **kargs):
        if self.txtfile:
            os.remove(os.path.join(settings.MEDIA_ROOT, self.txtfile.path))
        super(Question, self).delete(*args, **kargs)

class Answer(models.Model):
    content = models.TextField('질문 답변')
    create_date = models.DateTimeField('작성일')
    modify_date = models.DateTimeField('수정일', null=True,blank=True)
    user = models.ForeignKey(User,on_delete=models.CASCADE, null=True)
        
    # FK
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    
    def __str__(self):
        return f'Question : {self.question} / {self.content}'

# 문제에 대한 풀이
class Resolve(models.Model):
    subject = models.CharField(' 제목', max_length = 200)
    content = models.TextField('풀이 내용')
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    create_date =  models.DateTimeField('날짜')
    modify_date = models.DateTimeField(null=True,blank=True)
    
    #ForeignKey
    problem = models.ForeignKey(Problem, on_delete = models.CASCADE)
    
    #Echo ck STR
    def __str__(self):
        return f'{self.problem.subject} {self.problem.content}'

class Comment(models.Model):
    content = models.TextField('댓글 내용', null = True, blank = True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    create_date =  models.DateTimeField('날짜')
    subject = models.CharField(' 제목', max_length = 200)
    #ForeignKey
    resolve = models.ForeignKey(Resolve, null=True, blank=True, on_delete = models.CASCADE) # 문제 풀이에 대한 Comment
    answer = models.ForeignKey(Answer, null=True, blank=True, on_delete = models.CASCADE) # 질문 답변에 대한 Comment
    modify_date = models.DateTimeField(null=True,blank=True)    
    def __str__(self):
        return f'{self.content}'

cojung/views/answer_views.py
from django.shortcuts import render,redirect,get_object_or_404
from cojung.models import Question, Answer
from cojung.forms import AnswerForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.utils import timezone

@login_required(login_url='member:login')
def answer_create(request, question_id):
    question = get_object_or_404(Question, pk = question_id)
    if request.method == 'POST':
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.user = request.user
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            
            return redirect('cojung:question_detail', question_id = question.id)
    else:
        form = AnswerForm()
        
    context = {'question' : question, 'form' : form}
    return render(request, 'cojung/question_detail.html', context)

@login_required(login_url='member:login')
def answer_modify(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    
    if request.user != answer.user:
        messages.error(request, "수정권한이 없습니다! ")
        return redirect("cojung:question_detail", question_id = answer.question.id)

    if request.method == "POST":
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.user = request.user
            answer.modify_date = timezone.now()
            answer.save()
            return redirect("cojung:question_detail", question_id = answer.question.id)
    else:
        form = AnswerForm(instance=answer)
        
    context = {'answer' : answer, 'form' : form}
    return render(request, "cojung/answer_modify_form.html", context)

@login_required(login_url='member:login')
def answer_delete(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    
    if request.user != answer.user:
        messages.error(request, "삭제권한이 없습니다! ")
        return redirect("cojung:question_detail", question_id = answer.question.id)
    
    answer.delete()
    return redirect('cojung:question_detail', question_id = answer.question.id)

cojung/views/comment_views.py
from django.shortcuts import render,redirect,get_object_or_404
from cojung.models import Answer,Comment
from cojung.forms import CommentForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.utils import timezone

@login_required(login_url='member:login')
def comment_answer_create(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.user = request.user
            comment.create_date = timezone.now()
            comment.answer = answer
            comment.save()
            
            return redirect('cojung:question_detail', question_id = answer.question.id)
    else:
        form = CommentForm()
        
    context = {'answer' : answer, 'form' : form}

    return render(request, 'cojung/answer_listl.html', context)

@login_required(login_url="member:login")
def comment_answer_modify(request, comment_id):
    """
    "Comment" 수정 기능
    """
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.user:
        messages.error(request, "수정권한이 없습니다! ")
        return redirect("cojung:question_detail", question_id = comment.answer.question.id)
    
    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.user = request.user
            comment.modify_date = timezone.now()
            comment.save()
            
            return redirect("cojung:question_detail", question_id = comment.answer.question.id)
    else:
        form = CommentForm(instance=comment)
        
    context = {
        'comment' : comment,
        'form' : form
    }
    
    return render(request, "cojung/comment_modify_form.html", context)

@login_required(login_url="member:login")
def comment_answer_delete(request, comment_id):
    """
    "Comment" 삭제 기능
    """
    comment = get_object_or_404(Comment, pk=comment_id)
    
    if request.user != comment.user:
        messages.error(request, "삭제권한이 없습니다! ")
        return redirect("cojung:question_detail", question_id = comment.answer.question.id)
    
    comment.delete()
    return redirect("cojung:question_detail", question_id = comment.answer.question.id)

cojung/views/post_views.py
from django.shortcuts import render, redirect, get_object_or_404
from cojung.forms import ProblemForm, QuestionForm
from cojung.models import Problem, Language
from django.utils import timezone
from django.contrib.auth.decorators import login_required

@login_required(login_url='member:login')
def create_post(request):
    """cojung 글작성"""
    if request.method == 'POST':
        form = ProblemForm(request.POST, request.FILES)
        # 여기서 request.FILES 하고 save 아래에서 하니까 아래 코드 한 줄 필요 없음!
        if form.is_valid():
            problem = form.save(commit=False)
            problem.create_date = timezone.now()
            problem.user = request.user
            # problem.txtfile = request.FILES.get('txtfile') # 파일 업로드
            problem.save()
            # language add
            if len(request.POST.getlist('language', None)) == 1:
                # name="language", value=1  =>  {..., language=1, ...} 뽑아오는 코드
                # 다중 선택일 시 리스트로 반환 [1, 2, 3]  =>  getlist 사용
                # value가 int여야 함 (DB에는 id로 저장되기 때문에)
                problem.language.add(request.POST.get('language', None))
            else:
                languages = request.POST.getlist('language', None)
                for language_num in languages:
                    problem.language.add(language_num)
            return redirect('cojung:index')
    else:
        form = ProblemForm()
    
    language_list = Language.objects.all()
    context = {'form': form, 'language_list': language_list}
        
    return render(request, 'cojung/problem_form.html', context)

@login_required(login_url='member:login')
def create_question(request):
    """질문 작성"""
    if request.method == 'POST':
        form = QuestionForm(request.POST, request.FILES)
        if form.is_valid():
            question = form.save(commit=False)
            question.create_date = timezone.now()
            question.user = request.user  # user 정보 입력 안하면 에러 발생
            question.save()
            return redirect('cojung:question')
    else:
        form = QuestionForm()
        
    return render(request, 'cojung/question_form.html', {'form': form})

@login_required(login_url='member:login')
def create_question_problem(request, problem_id):
    """질문 작성"""
    problem = get_object_or_404(Problem, pk=problem_id)
    if request.method == 'POST':
        form = QuestionForm(request.POST, request.FILES)
        if form.is_valid():
            question = form.save(commit=False)
            question.create_date = timezone.now()
            question.user = request.user  # user 정보 입력 안하면 에러 발생
            question.problem = problem
            question.save()
            return redirect('cojung:question')
    else:
        form = QuestionForm()
        
    return render(request, 'cojung/problem_question_form.html', {'form': form})

cojung/views/resolve_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseNotAllowed
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone

from cojung.forms import ResolveForm,CommentForm
from cojung.models import Problem, Resolve, Comment


@login_required(login_url='member:login')
def Resolve_create(request, problem_id):
    problem = get_object_or_404(Problem, pk=problem_id)
    if request.method == "POST":
        form = ResolveForm(request.POST)
        if form.is_valid():
            resolve = form.save(commit=False)
            resolve.user = request.user  # author 속성에 로그인 계정 저장
            resolve.create_date = timezone.now()
            resolve.problem = problem
            resolve.save()
    else:
        return HttpResponseNotAllowed('Only POST is possible.')
    context = {'problem': problem, 'form': form}
    return render(request, 'cojung/resolve_list.html', context)


@login_required(login_url='member:login')
def comment_create_resolve(request, resolve_id):
    """
    pybo 답글댓글등록
    """
    resolve = get_object_or_404(Resolve, pk=resolve_id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.user = request.user
            comment.create_date = timezone.now()
            comment.resolve = resolve
            comment.save()
            return redirect('{}#comment_{}'.format(
                resolve_url('cojung:resolve_detail', problem_id=comment.resolve.problem.id), comment.id))
    else:
        form = CommentForm()
    context = {'form': form}
    return render(request, 'cojung/comment_form.html', context)

@login_required(login_url='member:login')
def resolve_detail(request,problem_id):
    """
    Problem 게시글
    """
    problem = get_object_or_404(Problem, pk=problem_id)
    context = {'problem':problem}
    return render(request,'cojung/resolve_list.html',context)

@login_required(login_url='member:login')
def resolve_modify(request, resolve_id):
    resolve = get_object_or_404(Resolve, pk=resolve_id)
    if request.user != resolve.user:
        messages.error(request, '수정권한이 없습니다')
        return redirect('cojung:resolve_detail', problem_id=resolve.problem.id)
    if request.method == "POST":
        form = ResolveForm(request.POST, instance=resolve)
        if form.is_valid():
            resovle = form.save(commit=False)
            resolve.modify_date = timezone.now()
            resolve.save()
            return redirect('{}#resolve_{}'.format(
                resolve_url('cojung:resolve_detail', problem_id=resolve.problem.id), resolve.id))
    else:
        form = ResolveForm(instance=resolve)
    context = {'resolve': resolve, 'form': form}
    return render(request, 'cojung/resolve_form.html', context)


@login_required(login_url='member:login')
def resolve_delete(request, resolve_id):
    resolve = get_object_or_404(Resolve, pk=resolve_id)
    if request.user != resolve.user:
        messages.error(request, '삭제권한이 없습니다')
    else:
        resolve.delete()
    return redirect('cojung:resolve_detail', problem_id=resolve.problem.id)

templates/cojung/answer_list.html
{% block content %}
<div>
    <strong>
        {{question.answer_set.count}} 개의 답변
    </strong>
</div>

<div>
    {% if question.answer_set.count > 0 %}
        {% for answer in question.answer_set.all %}
            <div style = "margin : 20px 0px">
                <strong>
                    {% if answer.user == question.user %} <strong style = 'color:#eb5d56'>[작성자]</strong>{% endif %} {{answer.user.username}}
                </strong>
                {% if answer.modify_date %}
                    <div style = "color:#c3c4c4">
                        {{answer.modify_date}}(수정됨)
                    </div>
                {% else %}
                    <div style = "color:#c3c4c4">
                        {{answer.create_date}}
                    </div>
                {% endif %}
                <div class = "bg-light" style = "padding:0px 20px; white-space : pre-line;">
                    {{answer.content}}
                    {% if request.user == answer.user %}
                    <div class = 'd-flex justify-content-end'>
                        <a href = "{% url 'cojung:answer_modify' answer.id %}" class="btn btn-outline-secondary" role="button" style = "margin: 0px 2px">수정</a>
                        <a href="#" data-uri = "{% url 'cojung:answer_delete' answer.id %}" class="delete_answer btn btn-outline-danger" role="button" style = "margin: 0px 2px">삭제</a>
                    </div>
                    {% endif %}
                </div>

                <!--Comment Line-->
                <div style = "font-size: small">
                    {% if answer.comment_set.count > 0 %}
                        {% for comment in answer.comment_set.all %}
                            <div style = 'padding: 20px 50px 20px 50px;'>
                                <i class="fa-brands fa-replyd" style = 'color : #5e66d8'></i>{% if comment.user == question.user %} <strong style = 'color:#eb5d56'>[작성자]</strong>{% endif %} <strong>{{comment.user.username}}</strong>
                                    {% if comment.modify_date %}
                                        <div style = "color:#c3c4c4">{{comment.modify_date}}(수정됨)</div>
                                    {% else %}
                                        <div style = "color:#c3c4c4">{{comment.create_date}}</div>
                                    {% endif %}
                                    <div style = 'padding-left : 30px; padding-right : 30px;'> 
                                        {{comment.content}} 
                                        {% if request.user == comment.user %}
                                        <div class = 'd-flex justify-content-end'>
                                            <a href = "{% url 'cojung:comment_answer_modify' comment.id %}" class="btn btn-outline-secondary" role="button" style = "margin: 0px 2px">수정</a>
                                            <a href="#" data-uri = "{% url 'cojung:comment_answer_delete' comment.id %}" class="delete_comment btn btn-outline-danger" role="button" style = "margin: 0px 2px">삭제</a>
                                        </div>
                                        {% endif %}
                                    </div>
                            </div>
                        {% endfor %}
                    {% endif %}
                    <!--답글 작성-->
                    <div style = 'padding : 20px 50px'>
                        <strong ><i class="fa-solid fa-reply"></i> 답글 달기 </strong>
                        {% include './comment_answer_form.html' %}
                    </div>
                </div>
            </div>
        {% endfor %}
    {% endif %}
</div>
{% endblock content %}

templates/cojung/problem.html
{% extends 'base.html' %}
{% load cojung_filter %}
{% block content%}
<div class="container my -3 " style="margin-top : 80px">
    {% if messages %}
      {% for message in messages %}
        {% if message.tags == "success" %}
          <div class='alert alert-success my-3' role='alert'>
              <strong>{{message.tag}}</strong>
              <ul>
                <li>{{message.message}}</li>
              </ul>
          </div>
        {% else %}
          <div class='alert alert-danger my-3' role='alert'>
              <strong>{{message.tag}}</strong>
              <ul>
                <li>{{message.message}}</li>
              </ul>
          </div>
        {% endif %}
      {% endfor %}
    {% endif %}
      
    <div class = 'd-flex justify-content-between'>
      <h2 class="py-2">{{problem.subject }}</h2>     
      <!--설정한 언어 확인-->                              
      <div class="dropdown pt-4">
        <button type="button" class="btn dropdown-toggle" data-toggle="dropdown">
          언어 보기
        </button>
        <div class="dropdown-menu"  style = 'max-height : 150px; overflow:auto;'>
          {% if problem.language.count > 0 %}
            {% for lang in problem.language.all %}
              <span class="dropdown-item-text">{{lang.name}}</span>
            {% endfor %}
          {% else %}
            <span class="dropdown-item-text">--------</span>
          {% endif %}
        </div>
      </div>
    </div>
    <hr>

    <div class="row">
      <div class="col-10">
        <div class="card my-3"> 
          <div class="card-body"> 
            <div class="card-text" style = 'z-index: 1;'>
              {{ problem.content|mark }}
            </div>
          </div>
        </div>
      </div>
      <div class="col-2" style = 'z-index: 2;'>
        <div class="d-flex justify-content-end"> 
          <div>
            <div class="badge bg-light text-dark p-2 text-start">
              <div class="mb-2">{{ problem.user.username }}</div>
              <div>{{ problem.create_date }}</div>
                <div class="my-3">
                    {% if  request.user  in problem.easy.all %}
                      <a href="{% url 'cojung:easy' problem.id  %}" class="btn btn-sm btn-success"> 쉬워요</a>
                          <span class="badge rounded-pill bg-danger">{{problem.easy.count}}</span>
                    {%elif request.user in problem.hard.all %}
                      <a href="{% url 'cojung:both' problem.id  %}" class="btn btn-sm btn-outline-secondary"> 쉬워요</a>
                        <span class="badge rounded-pill bg-danger">{{problem.easy.count}}</span>
                    {% else %}
                      <a href="{% url 'cojung:easy' problem.id  %}" class="btn btn-sm btn-outline-success"> 쉬워요</a>
                          <span class="badge rounded-pill bg-danger">{{problem.easy.count}}</span>
                    {%endif%} 
                </div>
                <div class="my-3">
                    {% if  request.user  in problem.hard.all %}
                      <a href="{% url 'cojung:hard' problem.id  %}" class="btn btn-sm btn-danger"> 어려워요</a>
                          <span class="badge rounded-pill bg-danger">{{problem.hard.count}}</span>
                    {%elif request.user in problem.easy.all %}
                      <a href="{% url 'cojung:both' problem.id  %}" class="btn btn-sm btn-outline-secondary"> 어려워요</a>
                        <span class="badge rounded-pill bg-danger">{{problem.hard.count}}</span>
                    {% else %}
                      <a href="{% url 'cojung:hard' problem.id  %}" class="btn btn-sm btn-outline-danger"> 어려워요</a>
                          <span class="badge rounded-pill bg-danger">{{problem.hard.count}}</span>
                    {%endif%}
                  <div class="my-3"> 
                    {% if request.user == problem.user %}
                    <a href="{% url 'cojung:problem_modify' problem.id  %}"
                      class="btn btn-sm btn-outline-secondary">수정</a>
                    <a href="javascript:void(0)" class="delete btn btn-sm btn-outline-secondary"
                      data-uri="{% url 'cojung:problem_delete' problem.id  %}">삭제</a>
                    {% endif %}
                  </div>
                </div>
              </div>
              <!-- txt 파일 보기 -->
              {% if problem.txtfile %}
                <div class = 'mt-2'>
                  <a href="{{ problem.txtfile.url }}" class="btn btn-outline-primary mb-2" target = "_blank"><i class="fa-regular fa-file"></i> 파일보기</a>
                </div>
              {% endif %}
            </div> <!--파일, user정보-->
          </div>
        </div>
      </div>
    </div>
      


    <div class="btn-group">
      <form action="{% url 'cojung:create_question_problem'  problem.id %}" method="post">
        {% csrf_token %}
        <input type="submit" value="질문하기" class="btn btn-light mx-2"/>
      </form>
    
      <form id = 'searchForm' method='get' action = "{% url 'cojung:question' %}">
          <button id= 'btn' name= 'problem_num' value = {{ problem.id }} class = "btn btn-light">질문보러가기</button> 
      </form>
    </div>
    
    <form action="{% url 'cojung:resolve_create' problem.id %}" method="post" class="my-3">
    {% csrf_token %}
      <input type="submit" value="      다른 사용자 풀이({{problem.resolve_set.count}}) 보러가기       " class="btn btn-dark"/>
    </form>
  
    <form action="{% url 'cojung:resolve_create' problem.id %}" method="post" class="my-1">
      {% csrf_token %}
      <div class="mb-3">
        <label for="content" class="form-label">풀이내용</label>
        <textarea {% if not user.is_authenticated %} disabled {% endif %}
        name="content" id="content" class="form-control" rows="10"></textarea>
      </div>
      <input type="submit" value="풀이등록" class="btn btn-light"/>
    </form>

    <form action="{% url 'cojung:index' %}" method="post" class="my-1">
      {% csrf_token %}
      <input type="submit" value="메인화면" class="btn btn-dark"/>
    </form>
{% endblock %}

{% comment %} {% block script %}
        <script>
          function openTextFile() {
            var input = document.createElement("input");

            input.type = "file";
            input.accept = "text/plain";

            input.onchange = function (event) {
              processFile(event.target.files[0]);
            };

            input.click();
          }

          function processFile(file) {
            var reader = new FileReader();

            reader.onload = function () {
              output.innerText = reader.result;
            };

            reader.readAsText(file, "euc-kr");
          }
        </script>
      {% endblock script %} {% endcomment %}


{% block script %}
<script type='text/javascript'>
const delete_elements = document.getElementsByClassName("delete");
Array.from(delete_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});
</script>
{% endblock %}

templates/cojung/resolve_list.html
{% extends 'base.html' %} 
{% load cojung_filter %} 
{% block content %}

<div style = "margin-top:80px">
  <!-- 문제 -->
  <h2 class="border-bottom py-2">{{ problem.subject }}</h2>
  <div class="card my-3">
    <div class="card-body">
      <div class="card-text">{{ problem.content|mark }}</div>
      <div class="d-flex justify-content-end">
        <div class="badge bg-light text-dark p-2 text-start">
          <div class="mb-2">{{ problem.user.username }}</div>
          <div>{{ question.create_date }}</div>
        </div>
      </div>
    </div>
  </div>

  <!--버튼 생성-->
  <form action="{% url 'cojung:detail' problem.id %}" method="post" class="my-1">
    {% csrf_token %}
    <input type="submit" value="문제로 돌아가기" class="btn btn-light"/>
  <form action="{% url 'cojung:index' %}" method="post" class="my-1">
    {% csrf_token %}
    <input type="submit" value="메인화면" class="btn btn-dark"/>

  <!-- 풀이 -->
  <h5 class="border-bottom my-3 py-2">
    {{problem.resolve_set.count}}개의 답변이 있습니다.
  </h5>
  {% for resolve in problem.resolve_set.all %}
  <a id="resolve_{{ resolve.id }}"></a>
  <div class="card my-3">
    <div class="card-body">
      <div class="card-text">{{ resolve.content|mark }}</div>
      <div class="d-flex justify-content-end">
        <div class="badge bg-light text-dark p-2 text-start">
          <div class="mb-2">{{ resolve.user.username }}</div>
          <div>{{ resolve.create_date }}</div>
          <div class="my-3">
              {% if request.user == resolve.user %}
                <a href="{% url 'cojung:resolve_modify' resolve.id  %}"
                class="btn btn-sm btn-outline-secondary">수정</a>
                  <a href="javascript:void(0)" class="delete btn btn-sm btn-outline-secondary "
                data-uri="{% url 'cojung:resolve_delete' resolve.id  %}">삭제</a>
              {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>
    {% if resolve.comment_set.count > 0 %}
      <div class="mt-3">
        {% for comment in resolve.comment_set.all %}
              <div class="comment py-2 text-muted">
                <span style="white-space: pre-line;">{{ comment.content }}</span>
                <span>
                - {{ comment.user }}, {{ comment.create_date }}
                </span>
              </div>
        {% endfor %}
      </div>
    {% endif %}
      <div>
      <a href="{% url 'cojung:comment_create_resolve' resolve.id  %}"
         class="small"><small>댓글 추가 ..</small></a>
      </div>
  {% endfor %}
</div>
{% endblock %}
{% block script %}
<script type='text/javascript'>
const delete_elements = document.getElementsByClassName("delete");
Array.from(delete_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});
</script>
{% endblock %}